# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "pxetool", primary: true do |pxetool|
    pxetool.vm.box = "fgrehm/trusty64-lxc"
    pxetool.vm.host_name = "pxetool.test.local"
    pxetool.vm.provision :shell, path: "./bootstrap.sh"
    pxetool.vm.synced_folder "../puppet-manifests/hiera/", "/var/lib/hiera", owner: "root", group: "root"
    pxetool.vm.synced_folder "../puppet-manifests/modules/", "/usr/share/puppet/modules", owner: "root", group: "root"
    pxetool.vm.synced_folder "../puppet-manifests/manifests/", "/etc/puppet/manifests", owner: "root", group: "root"
    pxetool.vm.synced_folder "../puppet-manifests/bin", "/etc/puppet/bin", owner: "root", group: "root"

    pxetool.vm.provider "lxc" do |v|
      v.container_name = 'pxetool'
      v.customize 'cgroup.memory.limit_in_bytes', '1024M'
    end
  end


  config.vm.define "slave01", primary: true do |slave01|
    slave01.vm.box = "fgrehm/trusty64-lxc"
    slave01.vm.host_name = "slave-01.test.local"
    slave01.vm.provision :shell, path: "./bootstrap.sh"

    slave01.vm.provider "lxc" do |v|
      v.container_name = 'slave01'
      v.customize 'cgroup.memory.limit_in_bytes', '2048M'
    end
  end


  config.vm.define "slave02", primary: true do |slave02|
    slave02.vm.box = "fgrehm/trusty64-lxc"
    slave02.vm.host_name = "slave-02.test.local"
    slave02.vm.provision :shell, path: "./bootstrap.sh"

    slave02.vm.provider "lxc" do |v|
      v.container_name = 'slave02'
      v.customize 'cgroup.memory.limit_in_bytes', '2048M'
    end
  end


  config.vm.define "slave03", primary: true do |slave03|
    slave03.vm.box = "fgrehm/trusty64-lxc"
    slave03.vm.host_name = "slave-03.test.local"
    slave03.vm.provision :shell, path: "./bootstrap.sh"

    slave03.vm.provider "lxc" do |v|
      v.container_name = 'slave03'
      v.customize 'cgroup.memory.limit_in_bytes', '2048M'
    end
  end


  config.vm.define "slave04", primary: true do |slave04|
    slave04.vm.box = "fgrehm/trusty64-lxc"
    slave04.vm.host_name = "slave-04.test.local"
    slave04.vm.provision :shell, path: "./bootstrap.sh"

    slave04.vm.provider "lxc" do |v|
      v.container_name = 'slave04'
      v.customize 'cgroup.memory.limit_in_bytes', '2048M'
    end
  end


  config.vm.define "slave05", primary: true do |slave05|
    slave05.vm.box = "fgrehm/trusty64-lxc"
    slave05.vm.host_name = "slave-05.test.local"
    slave05.vm.provision :shell, path: "./bootstrap.sh"

    slave05.vm.provider "lxc" do |v|
      v.container_name = 'slave05'
      v.customize 'cgroup.memory.limit_in_bytes', '2048M'
    end
  end


  config.vm.define "slave06", primary: true do |slave06|
    slave06.vm.box = "fgrehm/trusty64-lxc"
    slave06.vm.host_name = "slave-06.test.local"
    slave06.vm.provision :shell, path: "./bootstrap.sh"

    slave06.vm.provider "lxc" do |v|
      v.container_name = 'slave06'
      v.customize 'cgroup.memory.limit_in_bytes', '2048M'
    end
  end


  config.vm.define "slave07", primary: true do |slave07|
    slave07.vm.box = "fgrehm/trusty64-lxc"
    slave07.vm.host_name = "slave-07.test.local"
    slave07.vm.provision :shell, path: "./bootstrap.sh"

    slave07.vm.provider "lxc" do |v|
      v.container_name = 'slave07'
      v.customize 'cgroup.memory.limit_in_bytes', '2048M'
    end
  end


  config.vm.define "slave08", primary: true do |slave08|
    slave08.vm.box = "fgrehm/trusty64-lxc"
    slave08.vm.host_name = "slave-08.test.local"
    slave08.vm.provision :shell, path: "./bootstrap.sh"

    slave08.vm.provider "lxc" do |v|
      v.container_name = 'slave08'
      v.customize 'cgroup.memory.limit_in_bytes', '2048M'
    end
  end


  config.vm.define "slave09", primary: true do |slave09|
    slave09.vm.box = "fgrehm/trusty64-lxc"
    slave09.vm.host_name = "slave-09.test.local"
    slave09.vm.provision :shell, path: "./bootstrap.sh"

    slave09.vm.provider "lxc" do |v|
      v.container_name = 'slave09'
      v.customize 'cgroup.memory.limit_in_bytes', '2048M'
    end
  end


  config.vm.define "slave10", primary: true do |slave10|
    slave10.vm.box = "fgrehm/trusty64-lxc"
    slave10.vm.host_name = "slave-10.test.local"
    slave10.vm.provision :shell, path: "./bootstrap.sh"

    slave10.vm.provider "lxc" do |v|
      v.container_name = 'slave10'
      v.customize 'cgroup.memory.limit_in_bytes', '2048M'
    end
  end


  config.vm.define "slave11", primary: true do |slave11|
    slave11.vm.box = "fgrehm/trusty64-lxc"
    slave11.vm.host_name = "slave-11.test.local"
    slave11.vm.provision :shell, path: "./bootstrap.sh"

    slave11.vm.provider "lxc" do |v|
      v.container_name = 'slave11'
      v.customize 'cgroup.memory.limit_in_bytes', '2048M'
    end
  end

end
