# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "pxetool", primary: true do |pxetool|
    pxetool.vm.box = "fgrehm/trusty64-lxc"
    pxetool.vm.host_name = "pxetool.test.local"
    pxetool.vm.provision :shell, path: "./bootstrap.sh"
    pxetool.vm.synced_folder "../puppet-manifests/hiera/", "/var/lib/hiera", owner: "root", group: "root"
    pxetool.vm.synced_folder "../puppet-manifests/modules/", "/usr/share/puppet/modules", owner: "root", group: "root"
    pxetool.vm.synced_folder "../puppet-manifests/manifests/", "/etc/puppet/manifests", owner: "root", group: "root"
    pxetool.vm.synced_folder "../puppet-manifests/bin", "/etc/puppet/bin", owner: "root", group: "root"

    pxetool.vm.provider "lxc" do |v|
      v.container_name = 'pxetool'
      v.customize 'cgroup.memory.limit_in_bytes', '1024M'
    end
  end


  config.vm.define "slave01", primary: true do |slave01|
    slave01.vm.box = "fgrehm/trusty64-lxc"
    slave01.vm.host_name = "slave-01.test.local"
    slave01.vm.provision :shell, path: "./bootstrap.sh"

    slave01.vm.provider "lxc" do |v|
      v.container_name = 'slave01'
      v.customize 'cgroup.memory.limit_in_bytes', '2048M'
    end
  end


  config.vm.define "slave02", primary: true do |slave02|
    slave02.vm.box = "fgrehm/trusty64-lxc"
    slave02.vm.host_name = "slave-02.test.local"
    slave02.vm.provision :shell, path: "./bootstrap.sh"

    slave02.vm.provider "lxc" do |v|
      v.container_name = 'slave02'
      v.customize 'cgroup.memory.limit_in_bytes', '2048M'
    end
  end


  config.vm.define "slave03", primary: true do |slave03|
    slave03.vm.box = "fgrehm/trusty64-lxc"
    slave03.vm.host_name = "slave-03.test.local"
    slave03.vm.provision :shell, path: "./bootstrap.sh"

    slave03.vm.provider "lxc" do |v|
      v.container_name = 'slave03'
      v.customize 'cgroup.memory.limit_in_bytes', '2048M'
    end
  end


  config.vm.define "slave04", primary: true do |slave04|
    slave04.vm.box = "fgrehm/trusty64-lxc"
    slave04.vm.host_name = "slave-04.test.local"
    slave04.vm.provision :shell, path: "./bootstrap.sh"

    slave04.vm.provider "lxc" do |v|
      v.container_name = 'slave04'
      v.customize 'cgroup.memory.limit_in_bytes', '2048M'
    end
  end


  config.vm.define "slave05", primary: true do |slave05|
    slave05.vm.box = "fgrehm/trusty64-lxc"
    slave05.vm.host_name = "slave-05.test.local"
    slave05.vm.provision :shell, path: "./bootstrap.sh"

    slave05.vm.provider "lxc" do |v|
      v.container_name = 'slave05'
      v.customize 'cgroup.memory.limit_in_bytes', '2048M'
    end
  end

end
