VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "pxetool", primary: true do |pxetool|
    # PXE Tool port
    # pxetool.vm.network "forwarded_port", guest: 80, host: 8888, gateway_ports: true, host_ip: '*'
    pxetool.vm.box = "ubuntu-14-04-libvirt"
    pxetool.vm.host_name = "pxetool.test.local"
    pxetool.vm.provision :shell, path: "./bootstrap.sh"
    pxetool.vm.synced_folder "../puppet-manifests/hiera/", "/var/lib/hiera", type: "nfs"
    pxetool.vm.synced_folder "../puppet-manifests/modules/", "/usr/share/puppet/modules", type: "nfs"
    pxetool.vm.synced_folder "../puppet-manifests/manifests/", "/etc/puppet/manifests", type: "nfs"
    pxetool.vm.synced_folder "../puppet-manifests/bin", "/etc/puppet/bin", type: "nfs"

    pxetool.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 2
      v.nested = true
      v.volume_cache = 'unsafe'
      v.management_network_name = 'default'
      v.management_network_address = '192.168.122.0/24'
    end
  end

  config.vm.define "slave01" do |slave01|
    slave01.vm.box = "ubuntu-14-04-libvirt"
    slave01.vm.host_name = "slave-01.test.local"
    slave01.vm.provision :shell, path: "./bootstrap.sh", args: ENV['FACTER_ROLE']

    slave01.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 2
      v.nested = true
      v.volume_cache = 'unsafe'
      v.management_network_name = 'default'
      v.management_network_address = '192.168.122.0/24'
    end
  end

  config.vm.define "slave02" do |slave02|
    slave02.vm.box = "ubuntu-14-04-libvirt"
    slave02.vm.host_name = "slave-02.test.local"
    slave02.vm.provision :shell, path: "./bootstrap.sh", args: ENV['FACTER_ROLE']

    slave02.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 2
      v.nested = true
      v.volume_cache = 'unsafe'
      v.management_network_name = 'default'
      v.management_network_address = '192.168.122.0/24'
    end
  end

  config.vm.define "slave03" do |slave03|
    slave03.vm.box = "ubuntu-14-04-libvirt"
    slave03.vm.host_name = "slave-03.test.local"
    slave03.vm.provision :shell, path: "./bootstrap.sh", args: ENV['FACTER_ROLE']

    slave03.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 2
      v.nested = true
      v.volume_cache = 'unsafe'
      v.management_network_name = 'default'
      v.management_network_address = '192.168.122.0/24'
    end
  end

  config.vm.define "slave04" do |slave04|
    slave04.vm.box = "ubuntu-14-04-libvirt"
    slave04.vm.host_name = "slave-04.test.local"
    slave04.vm.provision :shell, path: "./bootstrap.sh", args: ENV['FACTER_ROLE']

    slave04.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 2
      v.nested = true
      v.volume_cache = 'unsafe'
      v.management_network_name = 'default'
      v.management_network_address = '192.168.122.0/24'
    end
  end

  config.vm.define "slave05" do |slave05|
    slave05.vm.box = "ubuntu-14-04-libvirt"
    slave05.vm.host_name = "slave-05.test.local"
    slave05.vm.provision :shell, path: "./bootstrap.sh", args: ENV['FACTER_ROLE']

    slave05.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 2
      v.nested = true
      v.volume_cache = 'unsafe'
      v.management_network_name = 'default'
      v.management_network_address = '192.168.122.0/24'
    end
  end

end
